name: Docker

on:
  push:
    branches:
      - "master"

  schedule:
    - cron:  '0 0 1 * *' # first of every month

jobs:
  docker:
    name: ${{ matrix.config.tags }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        r_version: [4.0.5, 4.2.2]

    steps:
    - uses: actions/checkout@v2
    
    - name: build from github
      run: |
        docker build https://github.com/rstudio/plumber.git#main \
        -t plumb \
        --build-arg R_VERSION=${{ matrix.r_version }} 

    # https://github.com/marketplace/actions/publish-docker
    - name: docker-push
      uses: elgohr/Publish-Docker-Github-Action@2.18
      with:
        name: jpdugo/plumber
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        cache: true
        workdir: "."
        tags: R${{ matrix.r_version }}
